-- Attest — the authorisation boundary, in version control.
--
-- Reproduced from the live project on 2026-09-10 and verified against it, not
-- written from memory. An earlier draft of this file guessed the column names
-- from the API payload and used `owner`; the database uses `user_id`, so
-- applying it would have built a second, incompatible schema. Read the database
-- before writing the migration.
--
-- `api/close.py` never uses a service-role key. It forwards the CALLER'S OWN
-- access token to PostgREST, so these policies are the boundary — not a second
-- line behind one. If they are wrong there is nothing else.
--
--     psql "$SUPABASE_DB_URL" -f db/policies.sql
--
-- Idempotent: safe to re-run.

-- ==========================================================================
-- Tables — as they exist
-- ==========================================================================

create table if not exists public.attest_closes (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null default auth.uid(),
  merchant           text not null,
  period             text not null,
  source             text not null,
  key_id_masked      text,
  records            integer not null default 0,
  batches_total      integer not null default 0,
  batches_tied       integer not null default 0,
  lines_total        integer not null default 0,
  lines_proven       integer not null default 0,
  claims_tested      integer not null default 0,
  claims_overturned  integer not null default 0,
  volume_paise       bigint  not null default 0,
  residual_paise     bigint  not null default 0,
  recoverable_paise  bigint  not null default 0,
  residual_bps       numeric not null default 0,
  attestable         boolean not null default false,
  evidence_supplied  text[]  not null default '{}'::text[],
  evidence_missing   text[]  not null default '{}'::text[],
  pack_html          text,
  created_at         timestamptz not null default now()
);

create table if not exists public.attest_findings (
  id             bigint generated by default as identity primary key,
  close_id       uuid not null references public.attest_closes(id) on delete cascade,
  user_id        uuid not null default auth.uid(),
  class          text not null,
  label          text not null,
  line_count     integer not null default 0,
  exposure_paise bigint  not null default 0,
  counterparty   text,
  deadline       date,
  created_at     timestamptz not null default now()
);

-- The seal outlives everything else. It is a claim that a document existed in a
-- given state at a given time, so deleting it destroys evidence the merchant
-- may later need themselves. Note that close_id deliberately carries NO
-- cascade: deleting a close must not take its seal with it.
create table if not exists public.attest_seals (
  digest      text primary key,
  user_id     uuid not null default auth.uid(),
  close_id    uuid,
  merchant    text not null,
  period      text not null,
  records     integer not null default 0,
  attestable  boolean not null default false,
  sealed_at   timestamptz not null default now()
);

create index if not exists attest_closes_user_idx    on public.attest_closes(user_id, created_at desc);
create index if not exists attest_findings_close_idx on public.attest_findings(close_id);

-- ==========================================================================
-- Row-level security
-- ==========================================================================

alter table public.attest_closes   enable row level security;
alter table public.attest_findings enable row level security;
alter table public.attest_seals    enable row level security;

-- ---- closes ---------------------------------------------------------------
drop policy if exists attest_closes_select on public.attest_closes;
create policy attest_closes_select on public.attest_closes
  for select using (user_id = (select auth.uid()));

-- `with check` and not merely `using`: without it a caller could insert a row
-- naming somebody else as the owner.
drop policy if exists attest_closes_insert on public.attest_closes;
create policy attest_closes_insert on public.attest_closes
  for insert with check (user_id = (select auth.uid()));

drop policy if exists attest_closes_update on public.attest_closes;
create policy attest_closes_update on public.attest_closes
  for update using (user_id = (select auth.uid()))
          with check (user_id = (select auth.uid()));

-- Deletion is how a merchant removes their financial data. The seal survives
-- it, by the absence of a cascade on attest_seals.close_id above.
drop policy if exists attest_closes_delete on public.attest_closes;
create policy attest_closes_delete on public.attest_closes
  for delete using (user_id = (select auth.uid()));

-- ---- findings -------------------------------------------------------------
drop policy if exists attest_findings_select on public.attest_findings;
create policy attest_findings_select on public.attest_findings
  for select using (user_id = (select auth.uid()));

drop policy if exists attest_findings_insert on public.attest_findings;
create policy attest_findings_insert on public.attest_findings
  for insert with check (user_id = (select auth.uid()));

drop policy if exists attest_findings_delete on public.attest_findings;
create policy attest_findings_delete on public.attest_findings
  for delete using (user_id = (select auth.uid()));

-- ---- seals: append-only, forever ------------------------------------------
-- A merchant can add a seal. Nobody can alter or remove one — not the merchant,
-- not us. That is what turns a self-contained checksum into something an
-- auditor can rely on: "was this exact digest recorded, and when?" must not be
-- editable after the fact.
--
-- There is NO update policy and NO delete policy here, and their absence IS the
-- guarantee. Adding either silently ends it. Verified against the live project:
-- only SELECT and INSERT exist.
drop policy if exists attest_seals_select on public.attest_seals;
create policy attest_seals_select on public.attest_seals
  for select using (user_id = (select auth.uid()));

drop policy if exists attest_seals_insert on public.attest_seals;
create policy attest_seals_insert on public.attest_seals
  for insert with check (user_id = (select auth.uid()));

-- ==========================================================================
-- Recommended hardening — NOT applied to the live project
-- ==========================================================================
-- Kept separate and commented deliberately. Each is a change in behaviour, and
-- a security file that quietly alters what the running system does is worse
-- than one that states the gap.
--
-- 1. FORCE row level security, so a future trigger or view running as the table
--    owner cannot read across tenants:
--
--      alter table public.attest_closes   force row level security;
--      alter table public.attest_findings force row level security;
--      alter table public.attest_seals    force row level security;
--
-- 2. Tie a finding to a close you actually own. Today `user_id = auth.uid()` is
--    checked but `close_id` is not, so a caller could attach a finding to
--    somebody else's close — invisible to them, but still wrong:
--
--      create policy attest_findings_insert on public.attest_findings
--        for insert with check (
--          user_id = (select auth.uid())
--          and exists (select 1 from public.attest_closes c
--                      where c.id = close_id and c.user_id = (select auth.uid()))
--        );
--
-- 3. Consider dropping attest_closes_update. A close is a statement about a
--    month as it was found; correcting it means running the month again, which
--    produces a new row and a new seal. An updatable close can disagree with
--    the seal that attests to it. Check the app does not rely on it first.
--
-- 4. Revoke public EXECUTE on the SECURITY DEFINER functions flagged by the
--    linter. Neither is exploitable — `is_admin()` keys on auth.uid() so an
--    anonymous caller always gets false, and `handle_new_user()` returns
--    `trigger` and cannot run outside a trigger — but neither should be in the
--    exposed API surface:
--
--      revoke execute on function public.is_admin()        from anon, authenticated;
--      revoke execute on function public.handle_new_user() from anon, authenticated;
