-- Attest — the authorisation boundary, in version control.
--
-- Reproduced from the live project on 2026-09-10 and verified against it, not
-- written from memory. An earlier draft of this file guessed the column names
-- from the API payload and used `owner`; the database uses `user_id`, so
-- applying it would have built a second, incompatible schema. Read the database
-- before writing the migration.
--
-- `api/close.py` never uses a service-role key. It forwards the CALLER'S OWN
-- access token to PostgREST, so these policies are the boundary — not a second
-- line behind one. If they are wrong there is nothing else.
--
--     psql "$SUPABASE_DB_URL" -f db/policies.sql
--
-- Idempotent: safe to re-run.

-- ==========================================================================
-- Tables — as they exist
-- ==========================================================================

create table if not exists public.attest_closes (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null default auth.uid(),
  merchant           text not null,
  period             text not null,
  source             text not null,
  key_id_masked      text,
  records            integer not null default 0,
  batches_total      integer not null default 0,
  batches_tied       integer not null default 0,
  lines_total        integer not null default 0,
  lines_proven       integer not null default 0,
  claims_tested      integer not null default 0,
  claims_overturned  integer not null default 0,
  volume_paise       bigint  not null default 0,
  residual_paise     bigint  not null default 0,
  recoverable_paise  bigint  not null default 0,
  residual_bps       numeric not null default 0,
  attestable         boolean not null default false,
  evidence_supplied  text[]  not null default '{}'::text[],
  evidence_missing   text[]  not null default '{}'::text[],
  -- The input fingerprint. See db/002_audit_trail.sql for why these
  -- exist and why `actor`/`ran_at` deliberately do not.
  readiness_verdict  text,
  claims_as_at       date,     -- recoverable_paise is relative to this date
  rows_in            integer,
  rows_read          integer,
  rows_rejected      integer,
  engine_version     text,
  ruleset_digest     text,
  pack_html          text,
  created_at         timestamptz not null default now()
);

create table if not exists public.attest_findings (
  id             bigint generated by default as identity primary key,
  close_id       uuid not null references public.attest_closes(id) on delete cascade,
  user_id        uuid not null default auth.uid(),
  class          text not null,
  label          text not null,
  line_count     integer not null default 0,
  exposure_paise bigint  not null default 0,
  counterparty   text,
  deadline       date,
  tier           text,          -- PROVEN | UNPROVEN | NEEDS_INPUT
  created_at     timestamptz not null default now()
);

-- The seal outlives everything else. It is a claim that a document existed in a
-- given state at a given time, so deleting it destroys evidence the merchant
-- may later need themselves. Note that close_id deliberately carries NO
-- cascade: deleting a close must not take its seal with it.
create table if not exists public.attest_seals (
  digest      text primary key,
  user_id     uuid not null default auth.uid(),
  close_id    uuid,
  merchant    text not null,
  period      text not null,
  records     integer not null default 0,
  attestable  boolean not null default false,
  sealed_at   timestamptz not null default now()
);

create index if not exists attest_closes_user_idx    on public.attest_closes(user_id, created_at desc);
create index if not exists attest_findings_close_idx on public.attest_findings(close_id);
create index if not exists attest_closes_partial_idx
  on public.attest_closes(user_id, created_at desc)
  where readiness_verdict is distinct from 'READY';

-- ==========================================================================
-- Row-level security
-- ==========================================================================

alter table public.attest_closes   enable row level security;
alter table public.attest_findings enable row level security;
alter table public.attest_seals    enable row level security;

-- ---- closes ---------------------------------------------------------------
drop policy if exists attest_closes_select on public.attest_closes;
create policy attest_closes_select on public.attest_closes
  for select using (user_id = (select auth.uid()));

-- `with check` and not merely `using`: without it a caller could insert a row
-- naming somebody else as the owner.
drop policy if exists attest_closes_insert on public.attest_closes;
create policy attest_closes_insert on public.attest_closes
  for insert with check (user_id = (select auth.uid()));

-- There is deliberately NO update policy on closes. A close is a statement
-- about a month as it was found; correcting it means running the month again,
-- which produces a new row and a new seal. An updatable close can disagree
-- with the seal that attests to it, and the seal is what an auditor trusts.
-- The statement below is kept so re-running this file removes an update policy
-- an older deployment may still have.
drop policy if exists attest_closes_update on public.attest_closes;

-- Deletion is how a merchant removes their financial data. The seal survives
-- it, by the absence of a cascade on attest_seals.close_id above.
drop policy if exists attest_closes_delete on public.attest_closes;
create policy attest_closes_delete on public.attest_closes
  for delete using (user_id = (select auth.uid()));

-- ---- findings -------------------------------------------------------------
drop policy if exists attest_findings_select on public.attest_findings;
create policy attest_findings_select on public.attest_findings
  for select using (user_id = (select auth.uid()));

-- `user_id` alone is not enough: without the close_id check a caller could
-- attach a finding to somebody else's close -- invisible to them, still wrong.
drop policy if exists attest_findings_insert on public.attest_findings;
create policy attest_findings_insert on public.attest_findings
  for insert with check (
    user_id = (select auth.uid())
    and exists (select 1 from public.attest_closes c
                where c.id = close_id and c.user_id = (select auth.uid()))
  );

drop policy if exists attest_findings_delete on public.attest_findings;
create policy attest_findings_delete on public.attest_findings
  for delete using (user_id = (select auth.uid()));

-- ---- seals: append-only, forever ------------------------------------------
-- A merchant can add a seal. Nobody can alter or remove one — not the merchant,
-- not us. That is what turns a self-contained checksum into something an
-- auditor can rely on: "was this exact digest recorded, and when?" must not be
-- editable after the fact.
--
-- There is NO update policy and NO delete policy here, and their absence IS the
-- guarantee. Adding either silently ends it. Verified against the live project:
-- only SELECT and INSERT exist.
drop policy if exists attest_seals_select on public.attest_seals;
create policy attest_seals_select on public.attest_seals
  for select using (user_id = (select auth.uid()));

drop policy if exists attest_seals_insert on public.attest_seals;
create policy attest_seals_insert on public.attest_seals
  for insert with check (user_id = (select auth.uid()));

-- ==========================================================================
-- Not applied, and why
-- ==========================================================================
-- Two items from the original hardening list are now applied above and are no
-- longer optional: findings are tied to a close you own, and closes cannot be
-- updated. What remains is stated here rather than left implied.
--
-- 1. FORCE row level security --- NOT applied.
--
--      alter table public.attest_closes   force row level security;
--      alter table public.attest_findings force row level security;
--      alter table public.attest_seals    force row level security;
--
--    This makes RLS apply to the table owner too. It guards against a future
--    SECURITY DEFINER function or view owned by `postgres` reading across
--    tenants -- of which this project has none, because it holds nothing but
--    Attest. Applying it would also stop maintenance and verification queries
--    that run as the owner from seeing any rows, which is a real cost today
--    against a hypothetical risk tomorrow. Revisit when the first such
--    function is added; that is the moment the trade-off flips.
--
-- 2. Revoking EXECUTE on `is_admin()` and `handle_new_user()` --- no longer
--    applicable. Those functions belonged to the shared project this app used
--    to live in. This project has no functions at all.
